### PR TITLE
feat: Adding Uno sample

### PR DESCRIPTION
**Pull request by nickrandolph**

### CODE REVIEW

**Comment by adrianhall** [comment]
The icons seem to be missing:

image

**Comment by adrianhall** [comment]
When I first loaded the solution, I got a brown banner at the top that said "one or more projects have changes that cannot be resolved by the project manager.  Reload projects" - the "Todo.Uno.Mobile" project had errors related to missing targets.

Clicking the "Reload projects" solved the problem.  Is this something we can do for the user, or do I need to instruct the user to do this?

**Comment by adrianhall** [comment]
(Icons were missing on first run through, but worked on subsequent run throughs - so transient error)

**Comment by adrianhall** [comment]
Microsoft.Identity.Client (MSAL) seems to have an issue with the net7.0-windows10.0.18362 TFM.

**Comment by adrianhall** [comment]
When going through the Android authentication tutorial, MSAL requires access to the "current activity" for this requirement:

``` csharp
        _identityClient = PublicClientApplicationBuilder
            .Create(Constants.ApplicationId)
            .WithAuthority(AzureCloudInstance.AzurePublic, "common")
            .WithRedirectUri($"msal{Constants.ApplicationId}://auth")
            .WithParentActivityOrWindow(() => Platform.CurrentActivity)
            .Build();
```

What's the equivalent in Uno?  `ApplicationActivity.GetCurrent(default).Result?`

**Comment by adrianhall** [comment]
Also in the authentication library, MSAL requires me to configure a new BrowserTabActivity - MAUI / Xamarin requires the following:

``` csharp
using Android.App;
using Android.Content;
using Microsoft.Identity.Client;

namespace TodoApp.Forms.Droid
{
    [Activity(Exported = true)]
    [IntentFilter(new[] { Intent.ActionView },
        Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
        DataHost = "auth",
        DataScheme = "msal{client-id}")]
    public class MsalActivity : BrowserTabActivity
    {
    }
}
```

What's the equivalent in Uno - probably creating a new class in TodoApp.Uno.Mobile\Android, but what are the contents?

**Comment by adrianhall** [comment]
Finally (for authentication, anyhow) - getting errors: 

``` text
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1082	There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm-aot'.	TodoApp.Uno	C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448	
Error	NETSDK1082	There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'.	TodoApp.Uno	C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448	
```

**Comment by adrianhall** [comment]
Solved the MSAL issues (including the TFM stuff) by simplifying the PublicClientApplicationBuilder to the following, and switching to Uno.WinUI.MSAL:

``` csharp
#if ANDROID || IOS
        string redirectUri = $"msal{Constants.ApplicationId}://auth";
#else
        string redirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient";
#endif
        _identityClient = PublicClientApplicationBuilder
            .Create(Constants.ApplicationId)
            .WithAuthority(AzureCloudInstance.AzurePublic, "common")
            .WithRedirectUri(redirectUri)
            .WithUnoHelpers()
            .Build();
```

New error during build: 

3>obj\Debug\net7.0-android\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-33\optional\androidx.window.extensions.jar
3>obj\Debug\net7.0-android\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-33\optional\androidx.window.sidecar.jar

My AndroidManifest.xml looks like this:

``` csharp
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <application>
	  <activity android:name="microsoft.identity.client.BrowserTabActivity" android:configChanges="orientation|screenSize" android:exported="true">
		  <intent-filter>
			  <action android:name="android.intent.action.VIEW" />
			  <category android:name="android.intent.category.DEFAULT" />
			  <category android:name="android.intent.category.BROWSABLE" />
			  <data android:scheme="msal2160b3eb-9ce1-4d3a-abc0-d37a45cd2e59" android:host="auth" />
		  </intent-filter>
	  </activity>
  </application>
</manifest>
```

And MainActivity.Android.cs looks like this:

``` csharp
using Android.App;
using Android.Content;
using Android.Views;
using Microsoft.Identity.Client;

namespace TodoApp.Uno
{
    [Activity(
			MainLauncher = true,
			ConfigurationChanges = global::Uno.UI.ActivityHelper.AllConfigChanges,
			WindowSoftInputMode = SoftInput.AdjustPan | SoftInput.StateHidden
		)]
	public class MainActivity : Microsoft.UI.Xaml.ApplicationActivity
	{
		protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
		{
			base.OnActivityResult(requestCode, resultCode, data);
			AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);
		}
	}
}
```

**Comment by nickrandolph** [comment]
> When I first loaded the solution, I got a brown banner at the top that said "one or more projects have changes that cannot be resolved by the project manager. Reload projects" - the "Todo.Uno.Mobile" project had errors related to missing targets.
> 
> Clicking the "Reload projects" solved the problem. Is this something we can do for the user, or do I need to instruct the user to do this?

There doesn't seem to be a workaround for this at the moment, so just need to flag as known warning for the user

**Comment by nickrandolph** [comment]
> Solved the MSAL issues (including the TFM stuff) by simplifying the PublicClientApplicationBuilder to the following, and switching to Uno.WinUI.MSAL:
> 
> ```cs
> #if ANDROID || IOS
>         string redirectUri = $"msal{Constants.ApplicationId}://auth";
> #else
>         string redirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient";
> #endif
>         _identityClient = PublicClientApplicationBuilder
>             .Create(Constants.ApplicationId)
>             .WithAuthority(AzureCloudInstance.AzurePublic, "common")
>             .WithRedirectUri(redirectUri)
>             .WithUnoHelpers()
>             .Build();
> ```
> 
> New error during build:
> 
> 3>obj\Debug\net7.0-android\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-33\optional\androidx.window.extensions.jar 3>obj\Debug\net7.0-android\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-33\optional\androidx.window.sidecar.jar
> 
> My AndroidManifest.xml looks like this:
> 
> ```cs
> <?xml version="1.0" encoding="utf-8"?>
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
>   <application>
> 	  <activity android:name="microsoft.identity.client.BrowserTabActivity" android:configChanges="orientation|screenSize" android:exported="true">
> 		  <intent-filter>
> 			  <action android:name="android.intent.action.VIEW" />
> 			  <category android:name="android.intent.category.DEFAULT" />
> 			  <category android:name="android.intent.category.BROWSABLE" />
> 			  <data android:scheme="msal2160b3eb-9ce1-4d3a-abc0-d37a45cd2e59" android:host="auth" />
> 		  </intent-filter>
> 	  </activity>
>   </application>
> </manifest>
> ```
> 
> And MainActivity.Android.cs looks like this:
> 
> ```cs
> using Android.App;
> using Android.Content;
> using Android.Views;
> using Microsoft.Identity.Client;
> 
> namespace TodoApp.Uno
> {
>     [Activity(
> 			MainLauncher = true,
> 			ConfigurationChanges = global::Uno.UI.ActivityHelper.AllConfigChanges,
> 			WindowSoftInputMode = SoftInput.AdjustPan | SoftInput.StateHidden
> 		)]
> 	public class MainActivity : Microsoft.UI.Xaml.ApplicationActivity
> 	{
> 		protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
> 		{
> 			base.OnActivityResult(requestCode, resultCode, data);
> 			AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);
> 		}
> 	}
> }
> ```

Yes, Uno.WinUI.MSAL is the main fix for getting auth to work. I'll send you the details

**Review by adrianhall — APPROVED** [review]

**Pull request merged**
